---

- name: Restart Tomcat
  systemd:
    name: tomcat
    state: restarted
  listen: "restart tomcat"

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  listen: "daemon reload"

- name: Stop Tomcat
  systemd:
    name: tomcat
    state: stopped
  listen: "stop tomcat"
