---

# Jenkins role defaults
jenkins_port: 8080
jenkins_version: "latest"
jenkins_home: /var/lib/jenkins
jenkins_url: "http://{{ ansible_host }}:{{ jenkins_port }}"

# Java and Maven variables
maven_package: maven
java_version: openjdk-21-jdk
java_home: /usr/lib/jvm/java-21-openjdk-amd64

# System dependencies for Jenkins
system_packages:
  - git
  - tar
  - wget
  - curl
  - gnupg
  - ca-certificates
  - "{{ java_version }}"
  - "{{ maven_package }}"

jenkins_plugins:
  - git
  - ssh-agent
  - maven-plugin
  - credentials-binding
