---
ansible_timeout: 30
ansible_user: ubuntu
ansible_become: true
ansible_connection: ssh
ansible_become_user: root
ansible_become_method: sudo
ansible_ssh_pipelining: true
ansible_become_ask_pass: false
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: ~/.ssh/aws-keypair.pem
ansible_ssh_common_args: -o ControlMaster=auto -o ControlPersist=60s