---
ansible_ssh_common_args: >-
  -o IdentitiesOnly=yes
  -o ProxyCommand="ssh -i {{ ansible_ssh_private_key_file }} -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p {{ hostvars['jenkins_server'].ansible_user }}@{{ hostvars['jenkins_server'].ansible_host }}"

tomcat_deploy_public_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/tomcat_deploy_key.pub') | trim }}"
